/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareerCounsellingRouteImport } from './routes/career-counselling'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as InstitutionPartnershipsRouteImport } from './routes/institution-partnerships'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PlacementAssistanceRouteImport } from './routes/placement-assistance'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TrainingProgramsRouteImport } from './routes/training-programs'
import { Route as WebsiteDevelopmentRouteImport } from './routes/website-development'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as InternshipsSlugRouteImport } from './routes/internships.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as TrainingProgramsSlugRouteImport } from './routes/training-programs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCounsellingRoute = CareerCounsellingRouteImport.update({
  id: '/career-counselling',
  path: '/career-counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionPartnershipsRoute = InstitutionPartnershipsRouteImport.update({
  id: '/institution-partnerships',
  path: '/institution-partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementAssistanceRoute = PlacementAssistanceRouteImport.update({
  id: '/placement-assistance',
  path: '/placement-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingProgramsRoute = TrainingProgramsRouteImport.update({
  id: '/training-programs',
  path: '/training-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDevelopmentRoute = WebsiteDevelopmentRouteImport.update({
  id: '/website-development',
  path: '/website-development',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const InternshipsSlugRoute = InternshipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InternshipsRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const TrainingProgramsSlugRoute = TrainingProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career-counselling': typeof CareerCounsellingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/digital-marketing': typeof DigitalMarketingRoute
  '/institution-partnerships': typeof InstitutionPartnershipsRoute
  '/internships': typeof InternshipsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/placement-assistance': typeof PlacementAssistanceRoute
  '/teams': typeof TeamsRoute
  '/training-programs': typeof TrainingProgramsRouteWithChildren
  '/website-development': typeof WebsiteDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/training-programs/$slug': typeof TrainingProgramsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career-counselling': typeof CareerCounsellingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/digital-marketing': typeof DigitalMarketingRoute
  '/institution-partnerships': typeof InstitutionPartnershipsRoute
  '/internships': typeof InternshipsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/placement-assistance': typeof PlacementAssistanceRoute
  '/teams': typeof TeamsRoute
  '/training-programs': typeof TrainingProgramsRouteWithChildren
  '/website-development': typeof WebsiteDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/training-programs/$slug': typeof TrainingProgramsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career-counselling': typeof CareerCounsellingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/digital-marketing': typeof DigitalMarketingRoute
  '/institution-partnerships': typeof InstitutionPartnershipsRoute
  '/internships': typeof InternshipsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/placement-assistance': typeof PlacementAssistanceRoute
  '/teams': typeof TeamsRoute
  '/training-programs': typeof TrainingProgramsRouteWithChildren
  '/website-development': typeof WebsiteDevelopmentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/training-programs/$slug': typeof TrainingProgramsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/career-counselling'
    | '/courses'
    | '/digital-marketing'
    | '/institution-partnerships'
    | '/internships'
    | '/jobs'
    | '/placement-assistance'
    | '/teams'
    | '/training-programs'
    | '/website-development'
    | '/auth/login'
    | '/auth/signup'
    | '/courses/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/training-programs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/career-counselling'
    | '/courses'
    | '/digital-marketing'
    | '/institution-partnerships'
    | '/internships'
    | '/jobs'
    | '/placement-assistance'
    | '/teams'
    | '/training-programs'
    | '/website-development'
    | '/auth/login'
    | '/auth/signup'
    | '/courses/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/training-programs/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/career-counselling'
    | '/courses'
    | '/digital-marketing'
    | '/institution-partnerships'
    | '/internships'
    | '/jobs'
    | '/placement-assistance'
    | '/teams'
    | '/training-programs'
    | '/website-development'
    | '/auth/login'
    | '/auth/signup'
    | '/courses/$slug'
    | '/internships/$slug'
    | '/jobs/$slug'
    | '/training-programs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CareerCounsellingRoute: typeof CareerCounsellingRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  InstitutionPartnershipsRoute: typeof InstitutionPartnershipsRoute
  InternshipsRoute: typeof InternshipsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  PlacementAssistanceRoute: typeof PlacementAssistanceRoute
  TeamsRoute: typeof TeamsRoute
  TrainingProgramsRoute: typeof TrainingProgramsRouteWithChildren
  WebsiteDevelopmentRoute: typeof WebsiteDevelopmentRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-counselling': {
      id: '/career-counselling'
      path: '/career-counselling'
      fullPath: '/career-counselling'
      preLoaderRoute: typeof CareerCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-partnerships': {
      id: '/institution-partnerships'
      path: '/institution-partnerships'
      fullPath: '/institution-partnerships'
      preLoaderRoute: typeof InstitutionPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-assistance': {
      id: '/placement-assistance'
      path: '/placement-assistance'
      fullPath: '/placement-assistance'
      preLoaderRoute: typeof PlacementAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-programs': {
      id: '/training-programs'
      path: '/training-programs'
      fullPath: '/training-programs'
      preLoaderRoute: typeof TrainingProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-development': {
      id: '/website-development'
      path: '/website-development'
      fullPath: '/website-development'
      preLoaderRoute: typeof WebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/internships/$slug': {
      id: '/internships/$slug'
      path: '/$slug'
      fullPath: '/internships/$slug'
      preLoaderRoute: typeof InternshipsSlugRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/training-programs/$slug': {
      id: '/training-programs/$slug'
      path: '/$slug'
      fullPath: '/training-programs/$slug'
      preLoaderRoute: typeof TrainingProgramsSlugRouteImport
      parentRoute: typeof TrainingProgramsRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface InternshipsRouteChildren {
  InternshipsSlugRoute: typeof InternshipsSlugRoute
}

const InternshipsRouteChildren: InternshipsRouteChildren = {
  InternshipsSlugRoute: InternshipsSlugRoute,
}

const InternshipsRouteWithChildren = InternshipsRoute._addFileChildren(
  InternshipsRouteChildren,
)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface TrainingProgramsRouteChildren {
  TrainingProgramsSlugRoute: typeof TrainingProgramsSlugRoute
}

const TrainingProgramsRouteChildren: TrainingProgramsRouteChildren = {
  TrainingProgramsSlugRoute: TrainingProgramsSlugRoute,
}

const TrainingProgramsRouteWithChildren =
  TrainingProgramsRoute._addFileChildren(TrainingProgramsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CareerCounsellingRoute: CareerCounsellingRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DigitalMarketingRoute: DigitalMarketingRoute,
  InstitutionPartnershipsRoute: InstitutionPartnershipsRoute,
  InternshipsRoute: InternshipsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  PlacementAssistanceRoute: PlacementAssistanceRoute,
  TeamsRoute: TeamsRoute,
  TrainingProgramsRoute: TrainingProgramsRouteWithChildren,
  WebsiteDevelopmentRoute: WebsiteDevelopmentRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
