import type { CourseMonth } from "./course-curricula";

export const artificialIntelligenceCurriculum: CourseMonth[] = [
  { month: 1, monthName: "AI & Python Fundamentals", weeks: [
    { title: "Introduction to Artificial Intelligence", topics: ["What is Artificial Intelligence?", "AI vs Machine Learning vs Deep Learning", "Types of AI", "Narrow AI", "General AI concepts", "AI applications", "AI in business", "AI career opportunities", "AI development lifecycle"], practicalTask: "Identify real-world AI applications and design a simple AI solution.", expectedOutcome: "Explain AI fundamentals and identify practical AI opportunities." },
    { title: "Python for AI", topics: ["Python introduction", "Variables", "Data types", "Operators", "Conditional statements", "Loops", "Functions", "Lists", "Tuples", "Sets", "Dictionaries"], practicalTask: "Build Python programs for AI/data processing.", expectedOutcome: "Use Python fundamentals for AI and data workflows." },
    { title: "Advanced Python for AI", topics: ["Object-oriented programming", "Classes and objects", "Modules", "Packages", "Exception handling", "File handling", "Lambda functions", "List comprehensions", "Virtual environments", "Git/GitHub fundamentals"], miniProject: "Build a Python-based data processing application.", expectedOutcome: "Build maintainable Python applications for AI projects." },
    { title: "NumPy, Pandas & Data Handling", topics: ["NumPy arrays", "Array operations", "Pandas Series", "DataFrames", "CSV/Excel data", "Filtering", "Sorting", "GroupBy", "Data transformation", "Basic data visualization"], assignment: "Perform data analysis using Python.", expectedOutcome: "Load, transform, and analyze data for AI applications." },
  ] },
  { month: 2, monthName: "Mathematics & Machine Learning", weeks: [
    { title: "Mathematics for AI", topics: ["Vectors", "Matrices", "Matrix operations", "Functions", "Derivatives", "Probability fundamentals", "Statistics fundamentals", "Optimization concepts"], practicalTask: "Implement mathematical operations using Python and NumPy.", expectedOutcome: "Understand the mathematics used by AI models." },
    { title: "Data Preprocessing", topics: ["Data cleaning", "Missing values", "Duplicate data", "Outliers", "Encoding", "Feature scaling", "Normalization", "Standardization", "Train/test split"], practicalTask: "Prepare a real-world dataset for AI modeling.", expectedOutcome: "Create clean, model-ready datasets." },
    { title: "Machine Learning Fundamentals", topics: ["What is Machine Learning?", "Supervised learning", "Unsupervised learning", "Reinforcement learning", "Regression", "Classification", "Clustering", "Model training", "Model prediction"], practicalTask: "Build a basic machine learning model.", expectedOutcome: "Explain core ML approaches and train a first model." },
    { title: "Machine Learning Algorithms", topics: ["Linear Regression", "Logistic Regression", "KNN", "Decision Trees", "Random Forest", "Support Vector Machines", "K-Means", "Model comparison"], miniProject: "Build a complete prediction/classification application.", expectedOutcome: "Select and compare common machine learning algorithms." },
  ] },
  { month: 3, monthName: "Deep Learning & Computer Vision", weeks: [
    { title: "Model Evaluation & Feature Engineering", topics: ["Accuracy", "Precision", "Recall", "F1-score", "Confusion matrix", "ROC-AUC", "Cross-validation", "Overfitting", "Underfitting", "Feature selection", "Feature engineering"], practicalTask: "Optimize and evaluate an ML model.", expectedOutcome: "Measure model quality and improve generalization." },
    { title: "Neural Networks", topics: ["Neural network fundamentals", "Artificial neurons", "Layers", "Activation functions", "Forward propagation", "Loss functions", "Backpropagation", "Gradient descent"], practicalTask: "Build a basic neural network.", expectedOutcome: "Explain and train a basic neural network." },
    { title: "TensorFlow / PyTorch", topics: ["Deep learning frameworks", "Dataset preparation", "Model creation", "Training", "Validation", "Loss monitoring", "Model evaluation", "Saving trained models"], assignment: "Build a neural network classification model.", expectedOutcome: "Train and save a deep learning model with a modern framework." },
    { title: "Computer Vision", topics: ["Introduction to computer vision", "Image processing", "Image preprocessing", "OpenCV fundamentals", "CNNs", "Convolution", "Pooling", "Image classification", "Object detection concepts"], miniProject: "Build an image classification application.", expectedOutcome: "Prepare image data and build a computer vision prototype." },
  ] },
  { month: 4, monthName: "NLP & Generative AI", weeks: [
    { title: "Natural Language Processing", topics: ["Introduction to NLP", "Text preprocessing", "Tokenization", "Stop words", "Stemming", "Lemmatization", "Text vectorization", "TF-IDF"], practicalTask: "Build a text classification system.", expectedOutcome: "Prepare text data and create a baseline NLP system." },
    { title: "Advanced NLP", topics: ["Sentiment analysis", "Text classification", "Named Entity Recognition", "Text similarity", "Word embeddings", "Introduction to transformers"], assignment: "Build a sentiment analysis or text classification application.", expectedOutcome: "Apply modern NLP techniques to real text problems." },
    { title: "Generative AI Fundamentals", topics: ["What is Generative AI?", "Generative AI vs traditional AI", "Large Language Models", "Text generation", "Image generation", "Audio generation", "Multimodal AI", "AI APIs", "Real-world Generative AI applications"], practicalTask: "Build a basic Generative AI application using an API.", expectedOutcome: "Understand generative models and integrate an AI API." },
    { title: "Prompt Engineering", topics: ["Prompt fundamentals", "Zero-shot prompting", "Few-shot prompting", "Role prompting", "Context engineering", "Structured outputs", "Prompt evaluation", "AI limitations", "Responsible AI", "Hallucinations"], miniProject: "Build an AI-powered content/assistant application.", expectedOutcome: "Create reliable prompts and evaluate responsible AI behavior." },
  ] },
  { month: 5, monthName: "LLMs, RAG & AI Agents", weeks: [
    { title: "Large Language Models", topics: ["LLM architecture concepts", "Transformers", "Tokens", "Embeddings", "Context windows", "Inference", "LLM APIs", "Model parameters", "Temperature", "System/user prompts"], practicalTask: "Build an application using an LLM API.", expectedOutcome: "Use LLM APIs with controlled prompts and parameters." },
    { title: "Embeddings & Vector Databases", topics: ["What are embeddings?", "Semantic search", "Vector databases", "Similarity search", "Document processing", "Chunking", "Retrieval"], practicalTask: "Create a semantic document search system.", expectedOutcome: "Build semantic retrieval over a document collection." },
    { title: "Retrieval-Augmented Generation", topics: ["What is RAG?", "RAG architecture", "Document ingestion", "Chunking", "Embeddings", "Retrieval", "Context injection", "Answer generation", "RAG evaluation"], assignment: "Build a document-based AI chatbot.", expectedOutcome: "Connect retrieval and generation into a grounded AI assistant." },
    { title: "AI Agents", topics: ["What are AI agents?", "Agent architecture", "Tools", "Function calling", "Memory concepts", "Planning", "Multi-step reasoning concepts", "Agent workflows", "Agent safety"], miniProject: "Build a simple AI agent that can use tools/APIs.", expectedOutcome: "Design an agent workflow with tools and safety boundaries." },
  ] },
  { month: 6, monthName: "AI Applications & Capstone", weeks: [
    { title: "AI Application Development", topics: ["AI application architecture", "Frontend + AI backend", "FastAPI/Flask", "Connecting AI models to APIs", "Authentication", "Database integration", "Logging", "Error handling"], practicalTask: "Build an AI-powered web application.", expectedOutcome: "Deliver an AI feature through a complete application architecture." },
    { title: "AI Deployment & MLOps Basics", topics: ["Model deployment", "API deployment", "Docker", "Environment variables", "Git/GitHub", "Cloud deployment concepts", "Model monitoring", "Performance monitoring", "AI security basics"], assignment: "Deploy an AI application using an API.", expectedOutcome: "Deploy and monitor an AI application responsibly." },
    { title: "End-to-End AI Capstone", topics: ["Problem Definition", "Data Collection", "Data Processing", "AI Model", "Application Development", "API Integration", "Testing", "Deployment"], assignment: "Develop a project such as an AI career assistant, study assistant, resume analyzer, document chatbot, customer support assistant, recommendation system, voice assistant, or educational tutor.", expectedOutcome: "Complete an end-to-end AI project from problem definition to deployment." },
    { title: "Final AI Project & Career Preparation", topics: ["Final project completion", "Model/application testing", "Performance optimization", "Deployment", "GitHub documentation", "Project presentation", "AI interview preparation", "Python interview preparation", "Machine Learning interview preparation", "Generative AI interview preparation", "Resume preparation", "Portfolio development", "Mock interview", "Final evaluation", "Certification"], practicalTask: "Present and defend the deployed AI capstone.", expectedOutcome: "Graduate with a documented AI project, portfolio, interview practice, and certification." },
  ] },
];
