import type { CourseMonth } from "./course-curricula";

export const cloudComputingCurriculum: CourseMonth[] = [
  { month: 1, monthName: "Cloud & Linux Fundamentals", weeks: [
    { title: "Introduction to Cloud Computing", topics: ["What is Cloud Computing?", "Evolution of cloud computing", "Cloud vs traditional infrastructure", "Benefits of cloud computing", "Public cloud", "Private cloud", "Hybrid cloud", "Community cloud", "Cloud service models", "IaaS", "PaaS", "SaaS"], practicalTask: "Identify suitable cloud solutions for different business requirements.", expectedOutcome: "Explain cloud models and match services to business needs." },
    { title: "Cloud Architecture & Virtualization", topics: ["Cloud architecture", "Regions", "Availability Zones", "Data centers", "Scalability", "Elasticity", "High availability", "Fault tolerance", "Virtual machines", "Hypervisors", "Virtualization concepts"], practicalTask: "Create and configure a virtual machine.", expectedOutcome: "Design resilient infrastructure using virtualization concepts." },
    { title: "Linux Fundamentals", topics: ["Linux introduction", "File system", "Files and directories", "Linux commands", "Permissions", "Users and groups", "Processes", "Package management", "Environment variables", "SSH"], practicalTask: "Configure a Linux server using SSH.", expectedOutcome: "Operate and secure a Linux server from the command line." },
    { title: "Networking Fundamentals", topics: ["Networking basics", "IP addresses", "IPv4 and IPv6", "Subnets", "DNS", "DHCP", "HTTP/HTTPS", "TCP/IP", "Ports", "Firewalls", "Load balancing concepts"], miniProject: "Design a basic cloud network architecture.", expectedOutcome: "Understand the network path between users, services, and infrastructure." },
  ] },
  { month: 2, monthName: "AWS & Azure Fundamentals", weeks: [
    { title: "AWS Fundamentals", topics: ["Introduction to AWS", "AWS account structure", "AWS Management Console", "IAM", "Users", "Groups", "Roles", "Policies", "Regions", "Availability Zones"], practicalTask: "Create IAM users and configure permissions.", expectedOutcome: "Navigate AWS and apply basic identity controls." },
    { title: "AWS Compute", topics: ["Amazon EC2", "Instance types", "AMIs", "Key pairs", "Security groups", "Elastic IP", "Auto Scaling", "Load Balancers", "Server deployment"], assignment: "Deploy a web application on EC2.", expectedOutcome: "Deploy and scale a web workload on AWS compute." },
    { title: "AWS Storage & Databases", topics: ["Amazon S3", "Buckets", "Objects", "Storage classes", "Versioning", "Lifecycle policies", "RDS", "Relational databases", "DynamoDB basics", "Backup concepts"], practicalTask: "Build an S3-based file storage system.", expectedOutcome: "Choose and configure cloud storage and database services." },
    { title: "Azure Fundamentals", topics: ["Introduction to Microsoft Azure", "Azure Portal", "Resource Groups", "Azure Virtual Machines", "Azure Storage", "Azure SQL", "Azure networking", "Azure identity", "Azure Monitor"], miniProject: "Deploy an application using Azure services.", expectedOutcome: "Map core AWS concepts to Azure services and deploy a workload." },
  ] },
  { month: 3, monthName: "Cloud Services & Security", weeks: [
    { title: "Cloud Networking", topics: ["Virtual Private Cloud", "VPC architecture", "Subnets", "Route tables", "Internet Gateway", "NAT Gateway", "Security Groups", "Network ACLs", "Load Balancers"], practicalTask: "Build a secure AWS VPC architecture.", expectedOutcome: "Design segmented, private, and public cloud networks." },
    { title: "Cloud Databases", topics: ["Cloud database concepts", "Relational databases", "NoSQL databases", "AWS RDS", "DynamoDB", "Azure SQL", "Database backups", "Replication", "High availability"], practicalTask: "Deploy and connect a cloud database to an application.", expectedOutcome: "Select a database architecture for availability and scale." },
    { title: "Cloud Security & IAM", topics: ["Cloud security fundamentals", "Identity and Access Management", "Least privilege", "Authentication", "Authorization", "Encryption", "Key management", "Secrets management", "Security monitoring", "Common cloud security risks"], assignment: "Secure a cloud application using IAM and encryption.", expectedOutcome: "Apply least privilege, encryption, and security monitoring." },
    { title: "Cloud Monitoring & Cost Management", topics: ["Cloud monitoring", "AWS CloudWatch", "Azure Monitor", "Logs", "Metrics", "Alerts", "Resource monitoring", "Cloud billing", "Cost optimization", "Reserved/discounted resources concepts"], miniProject: "Create a cloud monitoring and alerting setup.", expectedOutcome: "Monitor service health and control cloud spend." },
  ] },
  { month: 4, monthName: "Docker & Kubernetes", weeks: [
    { title: "Docker Fundamentals", topics: ["What is Docker?", "Containers vs virtual machines", "Docker architecture", "Images", "Containers", "Docker commands", "Docker Hub", "Dockerfiles"], practicalTask: "Containerize a web application.", expectedOutcome: "Build and run a portable containerized application." },
    { title: "Advanced Docker", topics: ["Docker Compose", "Volumes", "Networks", "Environment variables", "Multi-container applications", "Image optimization", "Container security", "Docker registries"], assignment: "Create a multi-container application.", expectedOutcome: "Compose and secure multi-service container deployments." },
    { title: "Kubernetes Fundamentals", topics: ["What is Kubernetes?", "Kubernetes architecture", "Cluster", "Nodes", "Pods", "Deployments", "Services", "Namespaces", "ConfigMaps", "Secrets"], practicalTask: "Deploy an application to a Kubernetes cluster.", expectedOutcome: "Deploy workloads and configuration to Kubernetes." },
    { title: "Kubernetes Advanced", topics: ["ReplicaSets", "Scaling", "Rolling updates", "Rollbacks", "Ingress", "Persistent volumes", "Health checks", "Kubernetes networking", "Kubernetes security"], miniProject: "Deploy a scalable application using Kubernetes.", expectedOutcome: "Operate a resilient, scalable Kubernetes service." },
  ] },
  { month: 5, monthName: "DevOps & Cloud Automation", weeks: [
    { title: "Git & GitHub", topics: ["Git fundamentals", "Repositories", "Commits", "Branches", "Merging", "Pull requests", "GitHub workflows", ".gitignore", "Collaboration"], practicalTask: "Create and manage a cloud project repository.", expectedOutcome: "Use version control for collaborative infrastructure work." },
    { title: "CI/CD", topics: ["What is CI/CD?", "Continuous Integration", "Continuous Delivery", "Continuous Deployment", "GitHub Actions", "Build pipelines", "Automated testing", "Deployment pipelines"], assignment: "Create a CI/CD pipeline for a cloud application.", expectedOutcome: "Automate testing and repeatable application delivery." },
    { title: "Infrastructure as Code", topics: ["Infrastructure as Code concepts", "Terraform introduction", "Providers", "Resources", "Variables", "Outputs", "State", "Terraform plan", "Terraform apply", "Infrastructure automation"], practicalTask: "Deploy cloud infrastructure using Terraform.", expectedOutcome: "Provision repeatable infrastructure from versioned code." },
    { title: "Cloud DevOps Integration", topics: ["GitHub", "Docker", "Kubernetes", "Terraform", "AWS/Azure", "CI/CD"], miniProject: "Build an automated cloud deployment pipeline.", expectedOutcome: "Combine development and infrastructure automation into one workflow." },
  ] },
  { month: 6, monthName: "Advanced Cloud & Capstone", weeks: [
    { title: "Serverless & Cloud-Native Architecture", topics: ["Serverless computing", "AWS Lambda", "Azure Functions", "API Gateway", "Event-driven architecture", "Microservices", "Cloud-native applications", "Message queues"], practicalTask: "Build a serverless API.", expectedOutcome: "Design event-driven services with managed cloud components." },
    { title: "Cloud Architecture & Production Deployment", topics: ["Scalable architecture", "High availability", "Disaster recovery", "Backup strategies", "Load balancing", "Auto scaling", "Monitoring", "Security", "Cost optimization"], assignment: "Design a production-ready cloud architecture.", expectedOutcome: "Plan a secure, resilient, and cost-aware production system." },
    { title: "Cloud Computing Capstone", topics: ["Application", "Docker", "Cloud Infrastructure", "Database", "CI/CD", "Monitoring", "Security", "Deployment"], assignment: "Develop a cloud project such as an LMS, e-commerce platform, job portal, file storage system, hospital system, student management system, scalable business application, or microservices application.", expectedOutcome: "Deliver a complete cloud project from application to deployment." },
    { title: "Final Deployment & Career Preparation", topics: ["Final project completion", "Production deployment", "Cloud security review", "Performance optimization", "Monitoring setup", "Documentation", "GitHub portfolio", "Cloud interview preparation", "AWS interview questions", "Azure interview questions", "Linux interview preparation", "DevOps interview preparation", "Resume preparation", "Mock interview", "Final project presentation", "Final evaluation", "Certification"], practicalTask: "Present and defend the production cloud deployment.", expectedOutcome: "Graduate with a documented cloud portfolio project and certification." },
  ] },
];
