import type { CourseMonth } from "./course-curricula";

export const machineLearningCurriculum: CourseMonth[] = [
  { month: 1, monthName: "Python & ML Fundamentals", weeks: [
    { title: "Python for Machine Learning", topics: ["Python introduction", "Variables", "Data types", "Operators", "Conditional statements", "Loops", "Functions", "Lists", "Dictionaries", "Tuples", "Sets"], practicalTask: "Build Python programs for basic data processing.", expectedOutcome: "Use Python fundamentals to prepare and manipulate data." },
    { title: "Advanced Python", topics: ["Object-oriented programming", "Classes and objects", "Modules", "Packages", "Exception handling", "File handling", "Lambda functions", "List comprehensions", "Virtual environments", "Git basics"], practicalTask: "Build a Python data-processing application.", expectedOutcome: "Build maintainable Python applications for ML workflows." },
    { title: "NumPy & Pandas", topics: ["NumPy arrays", "Indexing and slicing", "Mathematical operations", "Pandas Series", "DataFrames", "Reading CSV/Excel files", "Filtering", "Sorting", "GroupBy", "Merging datasets"], practicalTask: "Analyze a real-world dataset using Python.", expectedOutcome: "Load, inspect, transform, and analyze datasets." },
    { title: "Introduction to Machine Learning", topics: ["What is Machine Learning?", "AI vs ML vs Deep Learning", "Types of Machine Learning", "Supervised learning", "Unsupervised learning", "Reinforcement learning", "ML workflow", "Training data", "Testing data", "Features and labels"], miniProject: "Build a simple introductory ML prediction model.", expectedOutcome: "Explain the ML workflow and train a first model." },
  ] },
  { month: 2, monthName: "Mathematics, Statistics & Data Preparation", weeks: [
    { title: "Statistics for Machine Learning", topics: ["Mean", "Median", "Mode", "Variance", "Standard deviation", "Percentiles", "Probability", "Distributions", "Correlation", "Covariance"], practicalTask: "Perform statistical analysis on an ML dataset.", expectedOutcome: "Use statistics to understand distributions and relationships." },
    { title: "Mathematics for ML", topics: ["Linear algebra fundamentals", "Vectors", "Matrices", "Matrix operations", "Distance calculations", "Functions", "Derivatives", "Basic calculus concepts", "Optimization fundamentals"], practicalTask: "Implement basic mathematical operations using NumPy.", expectedOutcome: "Understand the mathematical ideas behind model training." },
    { title: "Data Preprocessing", topics: ["Data cleaning", "Missing values", "Duplicate data", "Outlier detection", "Encoding categorical variables", "Feature scaling", "Normalization", "Standardization", "Train/test split"], practicalTask: "Prepare a raw dataset for machine learning.", expectedOutcome: "Create a clean, correctly prepared training dataset." },
    { title: "Exploratory Data Analysis", topics: ["EDA", "Data distributions", "Correlation analysis", "Feature relationships", "Matplotlib", "Seaborn", "Visualization techniques", "Finding patterns", "Identifying useful features"], miniProject: "Complete EDA and preprocessing on a real-world dataset.", expectedOutcome: "Use EDA to select useful features and identify data quality issues." },
  ] },
  { month: 3, monthName: "Supervised Machine Learning", weeks: [
    { title: "Linear & Polynomial Regression", topics: ["Regression fundamentals", "Linear regression", "Multiple linear regression", "Polynomial regression", "Cost function", "Predictions", "Model training"], practicalTask: "Build a House Price Prediction model.", expectedOutcome: "Train regression models and interpret predictions." },
    { title: "Classification", topics: ["Classification concepts", "Logistic regression", "K-Nearest Neighbors", "Decision trees", "Classification workflow"], practicalTask: "Build a Customer/Student Classification System.", expectedOutcome: "Solve binary and multiclass classification problems." },
    { title: "Advanced Classification", topics: ["Support Vector Machines", "Naive Bayes", "Decision tree optimization", "Random Forest", "Feature importance"], practicalTask: "Compare multiple classification algorithms.", expectedOutcome: "Select and tune classification algorithms for a dataset." },
    { title: "Model Evaluation", topics: ["Accuracy", "Precision", "Recall", "F1-score", "Confusion matrix", "ROC curve", "AUC", "Cross-validation", "Bias and variance", "Overfitting", "Underfitting"], miniProject: "Build and evaluate a complete classification system.", expectedOutcome: "Evaluate model quality and diagnose generalization problems." },
  ] },
  { month: 4, monthName: "Advanced Machine Learning", weeks: [
    { title: "Feature Engineering", topics: ["Feature selection", "Feature extraction", "Creating new features", "Handling categorical features", "Scaling", "Transformation", "Feature importance", "Dimensionality reduction concepts"], practicalTask: "Improve an existing ML model using feature engineering.", expectedOutcome: "Create stronger features and improve model performance." },
    { title: "Ensemble Learning", topics: ["Ensemble learning concepts", "Bagging", "Boosting", "Random Forest", "Gradient Boosting", "AdaBoost", "XGBoost introduction", "Model comparison"], assignment: "Build an ensemble-based prediction model.", expectedOutcome: "Combine models and compare ensemble strategies." },
    { title: "Unsupervised Learning", topics: ["Clustering", "K-Means", "Hierarchical clustering", "DBSCAN", "Cluster evaluation", "Customer segmentation"], practicalTask: "Build a Customer Segmentation System.", expectedOutcome: "Discover groups and patterns without labeled data." },
    { title: "Dimensionality Reduction", topics: ["Why dimensionality reduction?", "PCA", "Feature reduction", "Visualization of high-dimensional data", "Selecting useful features"], miniProject: "Perform PCA and clustering on a real dataset.", expectedOutcome: "Reduce complex feature spaces while retaining useful information." },
  ] },
  { month: 5, monthName: "Deep Learning & AI", weeks: [
    { title: "Neural Network Fundamentals", topics: ["Introduction to neural networks", "Artificial neurons", "Layers", "Activation functions", "Forward propagation", "Loss functions", "Backpropagation", "Gradient descent"], practicalTask: "Build a basic neural network.", expectedOutcome: "Explain and train a basic neural network." },
    { title: "TensorFlow / PyTorch", topics: ["Deep learning frameworks", "Dataset preparation", "Model creation", "Training", "Validation", "Loss monitoring", "Model evaluation"], assignment: "Build a neural network classification model.", expectedOutcome: "Use a deep learning framework to train and validate a model." },
    { title: "Computer Vision", topics: ["Image data", "Image preprocessing", "CNN fundamentals", "Convolution", "Pooling", "Image classification", "Data augmentation"], miniProject: "Build an image classification model.", expectedOutcome: "Prepare image data and build a CNN-based classifier." },
    { title: "Natural Language Processing", topics: ["Introduction to NLP", "Text preprocessing", "Tokenization", "Stop words", "Stemming", "Lemmatization", "TF-IDF", "Text classification", "Sentiment analysis"], assignment: "Build a sentiment analysis system.", expectedOutcome: "Transform text into features and classify language data." },
  ] },
  { month: 6, monthName: "Deployment, MLOps & Capstone", weeks: [
    { title: "Machine Learning Deployment", topics: ["Saving ML models", "Pickle/joblib", "Flask/FastAPI", "Creating prediction APIs", "Connecting frontend with ML model", "API testing"], practicalTask: "Deploy an ML model through an API.", expectedOutcome: "Expose a trained model through a tested prediction service." },
    { title: "MLOps & Production Basics", topics: ["ML project structure", "Git/GitHub", "Model versioning", "Data versioning concepts", "Docker", "Environment management", "Monitoring basics", "Model performance tracking"], practicalTask: "Containerize an ML application using Docker.", expectedOutcome: "Package ML work for repeatable, monitored delivery." },
    { title: "End-to-End Machine Learning Capstone", topics: ["Problem Definition", "Data Collection", "Data Cleaning", "EDA", "Feature Engineering", "Model Training", "Evaluation", "Optimization", "Deployment"], assignment: "Develop a complete project such as churn, fraud, recommendation, segmentation, image, or sentiment analysis.", expectedOutcome: "Complete an end-to-end ML project from problem to deployment." },
    { title: "Final Project & Career Preparation", topics: ["Final project completion", "Model optimization", "API deployment", "GitHub documentation", "Project presentation", "ML interview preparation", "Python interview preparation", "SQL basics for ML roles", "Machine Learning interview questions", "Resume preparation", "Portfolio preparation", "Mock interview", "Final evaluation", "Certification"], practicalTask: "Present and defend the deployed ML capstone.", expectedOutcome: "Graduate with a documented project, portfolio, interview practice, and certification." },
  ] },
];
