import type { CourseMonth } from "./course-curricula";

export const sqlDataManagementCurriculum: CourseMonth[] = [
  { month: 1, monthName: "SQL Fundamentals & Database Design", weeks: [
    { title: "Introduction to Databases & SQL", topics: ["What is data?", "What is a database?", "What is DBMS?", "DBMS vs RDBMS", "SQL introduction", "MySQL introduction", "PostgreSQL introduction", "Databases", "Tables", "Rows", "Columns", "Primary keys", "Foreign keys", "Constraints", "Installing MySQL/PostgreSQL", "MySQL Workbench / database tools"], practicalTask: "Create a Student Management System database with Students, Courses, and Departments tables.", assignment: "Create your own database with at least 3 related tables.", expectedOutcome: "Understand relational database concepts and create a connected schema." },
    { title: "SQL Fundamentals", topics: ["CREATE DATABASE", "CREATE TABLE", "ALTER TABLE", "DROP TABLE", "INSERT", "SELECT", "UPDATE", "DELETE", "WHERE", "DISTINCT", "ORDER BY", "LIMIT", "Aliases"], practicalTask: "Create and manage an employee database: insert, update, delete, search, sort, and filter records.", miniProject: "Employee Management Database", expectedOutcome: "Write core SQL commands to manage structured data." },
    { title: "SQL Functions & Data Analysis", topics: ["Aggregate functions", "COUNT()", "SUM()", "AVG()", "MIN()", "MAX()", "GROUP BY", "HAVING", "CASE", "String functions", "Date functions", "Numeric functions"], practicalTask: "Analyze a sales database for totals, averages, extremes, employee/category results, and monthly sales.", miniProject: "Sales Analytics Database", expectedOutcome: "Summarize business data with SQL functions and grouped queries." },
    { title: "Joins & Relationships", topics: ["Database relationships", "One-to-one", "One-to-many", "Many-to-many", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN concepts", "SELF JOIN", "CROSS JOIN", "Multiple-table queries"], practicalTask: "Create Customers, Orders, Products, and Employees tables and generate meaningful reports.", assignment: "Build an E-Commerce Database Analysis project.", expectedOutcome: "Combine related tables and explain relational data relationships." },
  ] },
  { month: 2, monthName: "Advanced SQL & Data Management", weeks: [
    { title: "Advanced SQL", topics: ["Subqueries", "Nested queries", "Correlated subqueries", "Common Table Expressions", "CTEs", "Window functions", "ROW_NUMBER()", "RANK()", "DENSE_RANK()", "PARTITION BY", "Advanced filtering", "Complex queries"], practicalTask: "Analyze a business dataset for top customers, second-highest salary, department rankings, and monthly sales rankings.", assignment: "Solve 25+ SQL interview-style problems.", expectedOutcome: "Write reusable advanced queries for analytics and interviews." },
    { title: "Database Design & Normalization", topics: ["Database design principles", "Entity", "Attribute", "Relationship", "ER diagrams", "ER modeling", "Primary keys", "Foreign keys", "Candidate keys", "Composite keys", "Functional dependencies", "Normalization", "1NF", "2NF", "3NF", "BCNF", "Denormalization"], practicalTask: "Design a College Management System with Students, Faculty, Courses, Departments, Exams, and Results.", assignment: "Create an ER diagram and normalized database structure.", expectedOutcome: "Convert requirements into normalized, maintainable database designs." },
    { title: "Transactions, Security & Optimization", topics: ["Transactions", "COMMIT", "ROLLBACK", "SAVEPOINT", "ACID properties", "Concurrency", "Database locks", "Indexes", "Clustered vs non-clustered index concepts", "Query optimization", "Execution plans", "Views", "Stored procedures", "Functions", "Triggers", "Users", "Roles", "Permissions", "GRANT", "REVOKE", "SQL injection", "Parameterized queries", "Access control"], practicalTask: "Optimize slow SQL queries with indexes and execution plans, then secure access with roles and parameterized queries.", expectedOutcome: "Build safer, faster database systems with transactional integrity." },
    { title: "Real-World DBMS Capstone Project", topics: ["Requirement Analysis", "ER Diagram", "Database Design", "Normalization", "Table Creation", "Relationships", "SQL Queries", "Stored Procedures", "Views", "Indexes", "Security", "Testing", "Final Database Documentation"], assignment: "Build a complete College, Hospital, E-Commerce, Banking, or Job Portal database management system.", miniProject: "Real-World DBMS Capstone Project", expectedOutcome: "Deliver a documented database project with production-minded design, queries, security, and testing." },
  ] },
];
