import type { CourseMonth } from "./course-curricula";

export const webDevelopmentCurriculum: CourseMonth[] = [
  { month: 1, monthName: "HTML, CSS & Web Fundamentals", weeks: [
    { title: "Web Development Fundamentals", topics: ["What is Web Development?", "How websites work", "Frontend vs Backend", "Client vs Server", "Browser fundamentals", "HTTP/HTTPS", "Domains and hosting", "Introduction to HTML", "HTML document structure", "Headings", "Paragraphs", "Links", "Images", "Lists"], practicalTask: "Create a personal profile webpage using HTML.", assignment: "Build a simple Personal Portfolio Page.", expectedOutcome: "Understand how the web works and create a structured HTML page." },
    { title: "HTML5 & Forms", topics: ["HTML5 semantic elements", "Header", "Navigation", "Main", "Section", "Article", "Footer", "Tables", "Forms", "Input types", "Labels", "Buttons", "Form validation", "Audio and video", "Accessibility basics"], practicalTask: "Create a complete registration/contact form.", miniProject: "Student Registration Website", expectedOutcome: "Build semantic, accessible pages with usable forms." },
    { title: "CSS Fundamentals", topics: ["Introduction to CSS", "Selectors", "Colors", "Fonts", "Backgrounds", "Borders", "Margins", "Padding", "Box model", "Width and height", "Display", "Positioning", "CSS units"], practicalTask: "Convert a basic HTML page into a professionally styled website.", expectedOutcome: "Style web pages with a clear and maintainable CSS system." },
    { title: "Responsive Web Design", topics: ["Flexbox", "CSS Grid", "Responsive layouts", "Media queries", "Mobile-first design", "Responsive navigation", "Cards", "Buttons", "Hover effects", "Transitions", "Basic animations"], miniProject: "Responsive Business Website", expectedOutcome: "Create polished layouts that work across screen sizes." },
  ] },
  { month: 2, monthName: "JavaScript & APIs", weeks: [
    { title: "JavaScript Fundamentals", topics: ["JavaScript introduction", "Variables", "Data types", "Operators", "Conditions", "Loops", "Functions", "Arrays", "Objects"], practicalTask: "Build interactive JavaScript programs.", assignment: "Create a JavaScript Calculator.", expectedOutcome: "Use JavaScript logic to create interactive browser features." },
    { title: "Modern JavaScript", topics: ["ES6+", "let", "const", "Arrow functions", "Template literals", "Destructuring", "Spread/rest operators", "Array methods", "map()", "filter()", "reduce()", "Modules"], practicalTask: "Build a dynamic product/listing interface.", expectedOutcome: "Write modern, modular JavaScript using functional collection methods." },
    { title: "DOM & Browser Programming", topics: ["DOM", "Selecting elements", "Modifying HTML", "Events", "Event listeners", "Forms", "Form validation", "Local storage", "Session storage", "Dynamic content"], miniProject: "To-Do List Application with add, edit, delete, complete, and local storage features.", expectedOutcome: "Build stateful browser experiences using DOM APIs and storage." },
    { title: "APIs & Asynchronous JavaScript", topics: ["JSON", "HTTP requests", "REST API concepts", "Fetch API", "Promises", "Async/await", "Error handling", "Loading states", "API responses"], assignment: "Build a Weather / Public API Dashboard.", expectedOutcome: "Consume external APIs and handle asynchronous UI states." },
  ] },
  { month: 3, monthName: "React Frontend Development", weeks: [
    { title: "React Fundamentals", topics: ["What is React?", "React project setup", "Components", "JSX", "Props", "State", "Events", "Conditional rendering", "Lists", "Keys"], practicalTask: "Build a React component-based website.", expectedOutcome: "Create interfaces from reusable React components." },
    { title: "React Hooks & Forms", topics: ["useState", "useEffect", "Forms", "Controlled components", "Form validation", "Reusable components", "Component communication"], miniProject: "React Student Management Interface", expectedOutcome: "Manage React state, forms, and component communication." },
    { title: "React Routing & API Integration", topics: ["React Router", "Routes", "Navigation", "Dynamic routes", "API integration", "Fetch/Axios", "Loading states", "Error handling"], practicalTask: "Connect a React frontend to a public API.", expectedOutcome: "Build multi-page React experiences driven by API data." },
    { title: "Advanced React & UI Development", topics: ["Reusable components", "Custom hooks", "Context API", "State management concepts", "Protected routes", "Search", "Filtering", "Pagination", "Responsive React UI"], assignment: "Build a React E-Commerce Frontend.", expectedOutcome: "Deliver a responsive React application with production-style UI patterns." },
  ] },
  { month: 4, monthName: "Backend Development", weeks: [
    { title: "Node.js Fundamentals", topics: ["What is Node.js?", "Node.js architecture", "npm", "Package management", "Modules", "File system", "Environment variables", "HTTP server", "Creating a Node.js application"], practicalTask: "Create a basic Node.js server.", expectedOutcome: "Understand server-side JavaScript and Node project structure." },
    { title: "Express.js", topics: ["Express.js", "Application setup", "Routes", "Middleware", "Request/response", "Parameters", "Query parameters", "Error handling", "Project structure"], practicalTask: "Build a REST API using Express.", expectedOutcome: "Create organized backend routes and middleware." },
    { title: "REST APIs", topics: ["REST architecture", "GET", "POST", "PUT", "PATCH", "DELETE", "Status codes", "JSON responses", "API validation", "API testing", "Postman"], miniProject: "Student Management REST API", expectedOutcome: "Design and test predictable REST endpoints." },
    { title: "Authentication & Authorization", topics: ["Authentication", "Authorization", "Password hashing", "JWT", "Login", "Registration", "Logout", "Protected routes", "Role-based access", "Admin/user permissions", "Basic web security"], assignment: "Build a User Authentication System.", expectedOutcome: "Secure users, routes, and roles in a backend application." },
  ] },
  { month: 5, monthName: "Database & Full Stack Development", weeks: [
    { title: "SQL & PostgreSQL", topics: ["Database fundamentals", "PostgreSQL", "Tables", "Primary keys", "Foreign keys", "Relationships", "CRUD", "SQL queries", "Joins", "Aggregation"], practicalTask: "Create a PostgreSQL database for a web application.", expectedOutcome: "Design and query relational data for web applications." },
    { title: "Backend + Database Integration", topics: ["Connecting Node.js to PostgreSQL", "Database queries", "CRUD APIs", "Data validation", "Relationships", "Error handling", "Database security", "Environment variables"], assignment: "Create a Full CRUD Web Application.", expectedOutcome: "Persist and validate application data through an API." },
    { title: "Full Stack Integration", topics: ["React + Node.js + Express + PostgreSQL", "Frontend/backend communication", "API integration", "Authentication integration", "Protected pages", "User dashboard", "Error handling", "Loading states", "Form submission"], assignment: "Build a Full Stack Student/Employee Management System.", expectedOutcome: "Connect frontend, backend, authentication, and database layers." },
    { title: "Git, GitHub & Docker", topics: ["Git fundamentals", "Repositories", "Branches", "Commits", "Pull Requests", "GitHub collaboration", "What is Docker?", "Images", "Containers", "Dockerfile", "Docker Compose", "Environment variables"], practicalTask: "Containerize the full-stack application and push it to GitHub.", expectedOutcome: "Version, collaborate on, and containerize a full-stack project." },
  ] },
  { month: 6, monthName: "Deployment & Capstone", weeks: [
    { title: "Web Deployment", topics: ["Hosting fundamentals", "Frontend deployment", "Backend deployment", "Database deployment", "Environment variables", "Production builds", "Domain concepts", "HTTPS", "Deployment troubleshooting"], practicalTask: "Deploy the frontend and backend application.", expectedOutcome: "Ship a full-stack application to a production environment." },
    { title: "Production Web Development", topics: ["Performance optimization", "Code organization", "Security basics", "CORS", "Rate limiting concepts", "Input validation", "Error logging", "SEO fundamentals", "Responsive testing", "Browser testing"], assignment: "Optimize and prepare a full-stack application for production.", expectedOutcome: "Improve reliability, security, performance, and accessibility." },
    { title: "Full Stack Capstone Project", topics: ["Project idea selection", "Requirement analysis", "UI/UX planning", "Database design", "Frontend development", "Backend development", "API development", "Authentication", "Database integration", "GitHub repository", "Testing"], assignment: "Build an e-commerce platform, job portal, learning management system, or online service platform.", miniProject: "Full Stack Capstone Project", expectedOutcome: "Plan and build a complete portfolio-grade web application." },
    { title: "Final Deployment & Career Preparation", topics: ["Final project completion", "Testing", "Bug fixing", "Production deployment", "GitHub documentation", "README creation", "Portfolio website", "Resume preparation", "Web development interview questions", "HTML/CSS interview preparation", "JavaScript interview preparation", "React interview preparation", "Node.js interview preparation", "SQL interview preparation", "Mock interview", "Project presentation", "Final evaluation", "Certification"], practicalTask: "Present and defend the deployed final project.", expectedOutcome: "Graduate with a documented, deployed portfolio project and interview readiness." },
  ] },
];
