import type { CourseMonth } from "./course-curricula";

export const gitGithubCurriculum: CourseMonth[] = [
  { month: 1, monthName: "Git & GitHub", weeks: [
    { title: "Git Fundamentals", topics: ["What is Version Control?", "Why Git is used", "Git vs GitHub", "Installing Git", "Git configuration", "Git Bash / Terminal", "Creating a Git repository", "git init", "git status", "git add", "git commit", "Commit messages", "Viewing commit history", "git log", "Working directory", "Staging area", "Local repository"], practicalTask: "Initialize a small project, stage files, create commits, view history, modify files, and commit changes again.", assignment: "Create a personal project repository and maintain at least 5 meaningful commits.", expectedOutcome: "Use Git locally to track changes with clear, useful commit history." },
    { title: "GitHub & Remote Repositories", topics: ["What is GitHub?", "Creating a GitHub account", "Creating repositories", "Public vs private repositories", "Connecting local Git to GitHub", "git remote", "git push", "git pull", "git fetch", "git clone", "README files", ".gitignore", "Repository organization", "GitHub profile basics"], practicalTask: "Create a GitHub repository, connect it locally, push updates, clone it, and pull changes.", miniProject: "Create a professional GitHub repository with a README, installation instructions, technologies, screenshots, project structure, and usage instructions.", expectedOutcome: "Manage remote repositories and present projects professionally on GitHub." },
    { title: "Branching & Team Collaboration", topics: ["Why branches are used", "Creating branches", "git branch", "git checkout", "git switch", "Merging branches", "git merge", "Branch naming conventions", "Feature branches", "Main/master branch", "Pull Requests", "Code review", "GitHub Issues", "GitHub Projects", "Collaboration workflow"], practicalTask: "Practice main → feature branch → development → Pull Request → Review → Merge.", miniProject: "Work in a team repository and complete a feature using a separate branch.", expectedOutcome: "Collaborate through branches, pull requests, reviews, issues, and merges." },
    { title: "Advanced Git & Professional Workflow", topics: ["Merge conflicts", "Resolving conflicts", "git diff", "git stash", "git reset", "git revert", "Undoing changes safely", "Commit best practices", "Branch management", "Tags", "Releases", "GitHub Actions introduction", "GitHub security basics", "Professional repository management", "Open-source contribution basics"], practicalTask: "Intentionally create a merge conflict, resolve it, commit the resolution, push changes, and complete the pull request.", assignment: "Create a Professional GitHub Portfolio Repository with at least two projects, documentation, screenshots, clean structure, issues, and a branching workflow.", miniProject: "Professional GitHub Portfolio Repository", expectedOutcome: "Resolve conflicts safely and maintain a portfolio-ready collaborative repository." },
  ] },
];
