UPDATE public.courses
SET title = 'SQL & Data Management Systems',
    short_description = 'Learn SQL and database management from fundamentals to advanced queries, design, optimization, and real-world DBMS projects.',
    full_description = 'Learn SQL and Database Management Systems from the fundamentals to advanced database development. This program covers relational databases, SQL queries, database design, normalization, joins, subqueries, stored procedures, views, transactions, indexing, database security, optimization and real-world database projects.',
    level = 'Beginner', duration = '2 Months | 8 Weeks', published_at = COALESCE(published_at, now())
WHERE slug = 'sql-database-management';

INSERT INTO public.course_weeks (course_id, week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
SELECT c.id, v.week_number, v.month_number, v.title, v.topics, v.practical_task, v.assignment, v.mini_project, v.expected_outcome
FROM public.courses c
CROSS JOIN (VALUES
(1,1,'Introduction to Databases & SQL',ARRAY['What is data?','What is a database?','What is DBMS?','DBMS vs RDBMS','SQL introduction','MySQL introduction','PostgreSQL introduction','Database','Tables','Rows','Columns','Primary keys','Foreign keys','Constraints','Installing MySQL/PostgreSQL','MySQL Workbench / database tools']::text[],'Create a Student Management System database with Students, Courses, and Departments tables.','Create your own database with at least 3 related tables.',NULL,'Understand relational database concepts and create a connected schema.'),
(2,1,'SQL Fundamentals',ARRAY['CREATE DATABASE','CREATE TABLE','ALTER TABLE','DROP TABLE','INSERT','SELECT','UPDATE','DELETE','WHERE','DISTINCT','ORDER BY','LIMIT','Aliases']::text[],'Create and manage an employee database: insert, update, delete, search, sort, and filter records.',NULL,'Employee Management Database', 'Write core SQL commands to manage structured data.'),
(3,1,'SQL Functions & Data Analysis',ARRAY['Aggregate functions','COUNT()','SUM()','AVG()','MIN()','MAX()','GROUP BY','HAVING','CASE','String functions','Date functions','Numeric functions']::text[],'Analyze a sales database for totals, averages, extremes, employee/category results, and monthly sales.',NULL,'Sales Analytics Database','Summarize business data with SQL functions and grouped queries.'),
(4,1,'Joins & Relationships',ARRAY['Database relationships','One-to-one','One-to-many','Many-to-many','INNER JOIN','LEFT JOIN','RIGHT JOIN','FULL OUTER JOIN concepts','SELF JOIN','CROSS JOIN','Multiple-table queries']::text[],'Create Customers, Orders, Products, and Employees tables and generate meaningful reports.','Build an E-Commerce Database Analysis project.',NULL,'Combine related tables and explain relational data relationships.'),
(5,2,'Advanced SQL',ARRAY['Subqueries','Nested queries','Correlated subqueries','Common Table Expressions','CTEs','Window functions','ROW_NUMBER()','RANK()','DENSE_RANK()','PARTITION BY','Advanced filtering','Complex queries']::text[],'Analyze a business dataset for top customers, second-highest salary, department rankings, and monthly sales rankings.','Solve 25+ SQL interview-style problems.',NULL,'Write reusable advanced queries for analytics and interviews.'),
(6,2,'Database Design & Normalization',ARRAY['Database design principles','Entity','Attribute','Relationship','ER diagrams','ER modeling','Primary keys','Foreign keys','Candidate keys','Composite keys','Functional dependencies','Normalization','1NF','2NF','3NF','BCNF','Denormalization']::text[],'Design a College Management System with Students, Faculty, Courses, Departments, Exams, and Results.','Create an ER diagram and normalized database structure.',NULL,'Convert requirements into normalized, maintainable database designs.'),
(7,2,'Transactions, Security & Optimization',ARRAY['Transactions','COMMIT','ROLLBACK','SAVEPOINT','ACID properties','Concurrency','Database locks','Indexes','Clustered vs non-clustered index concepts','Query optimization','Execution plans','Views','Stored procedures','Functions','Triggers','Users','Roles','Permissions','GRANT','REVOKE','SQL injection','Parameterized queries','Access control']::text[],'Optimize slow SQL queries with indexes and execution plans, then secure access with roles and parameterized queries.',NULL,NULL,'Build safer, faster database systems with transactional integrity.'),
(8,2,'Real-World DBMS Capstone Project',ARRAY['Requirement Analysis','ER Diagram','Database Design','Normalization','Table Creation','Relationships','SQL Queries','Stored Procedures','Views','Indexes','Security','Testing','Final Database Documentation']::text[],NULL,'Build a complete College, Hospital, E-Commerce, Banking, or Job Portal database management system.','Real-World DBMS Capstone Project','Deliver a documented database project with production-minded design, queries, security, and testing.')
) AS v(week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
WHERE c.slug = 'sql-database-management'
ON CONFLICT (course_id, week_number) DO UPDATE SET
  month_number = EXCLUDED.month_number, title = EXCLUDED.title, topics = EXCLUDED.topics,
  practical_task = EXCLUDED.practical_task, assignment = EXCLUDED.assignment,
  mini_project = EXCLUDED.mini_project, expected_outcome = EXCLUDED.expected_outcome, updated_at = now();
