UPDATE public.courses
SET title = 'Web Development',
    short_description = 'Learn modern web development from fundamentals to deployed full-stack applications with HTML, CSS, JavaScript, React, Node.js, PostgreSQL, APIs, Git, and Docker.',
    full_description = 'Learn modern web development from the fundamentals to building and deploying complete full-stack web applications. Students will learn frontend development, responsive UI design, JavaScript programming, React, backend development with Node.js and Express, databases, REST APIs, authentication, Git/GitHub, Docker and deployment.',
    level = 'Beginner', duration = '6 Months | 24 Weeks', published_at = COALESCE(published_at, now())
WHERE slug = 'web-development';

INSERT INTO public.course_weeks (course_id, week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
SELECT c.id, v.week_number, v.month_number, v.title, v.topics, v.practical_task, v.assignment, v.mini_project, v.expected_outcome
FROM public.courses c
CROSS JOIN (VALUES
(1,1,'Web Development Fundamentals',ARRAY['What is Web Development?','How websites work','Frontend vs Backend','Client vs Server','Browser fundamentals','HTTP/HTTPS','Domains and hosting','Introduction to HTML','HTML document structure','Headings','Paragraphs','Links','Images','Lists']::text[],'Create a personal profile webpage using HTML.','Build a simple Personal Portfolio Page.',NULL,'Understand how the web works and create a structured HTML page.'),
(2,1,'HTML5 & Forms',ARRAY['HTML5 semantic elements','Header','Navigation','Main','Section','Article','Footer','Tables','Forms','Input types','Labels','Buttons','Form validation','Audio and video','Accessibility basics']::text[],'Create a complete registration/contact form.',NULL,'Student Registration Website','Build semantic, accessible pages with usable forms.'),
(3,1,'CSS Fundamentals',ARRAY['Introduction to CSS','Selectors','Colors','Fonts','Backgrounds','Borders','Margins','Padding','Box model','Width and height','Display','Positioning','CSS units']::text[],'Convert a basic HTML page into a professionally styled website.',NULL,NULL,'Style web pages with a clear and maintainable CSS system.'),
(4,1,'Responsive Web Design',ARRAY['Flexbox','CSS Grid','Responsive layouts','Media queries','Mobile-first design','Responsive navigation','Cards','Buttons','Hover effects','Transitions','Basic animations']::text[],NULL,NULL,'Responsive Business Website','Create polished layouts that work across screen sizes.'),
(5,2,'JavaScript Fundamentals',ARRAY['JavaScript introduction','Variables','Data types','Operators','Conditions','Loops','Functions','Arrays','Objects']::text[],'Build interactive JavaScript programs.','Create a JavaScript Calculator.',NULL,'Use JavaScript logic to create interactive browser features.'),
(6,2,'Modern JavaScript',ARRAY['ES6+','let','const','Arrow functions','Template literals','Destructuring','Spread/rest operators','Array methods','map()','filter()','reduce()','Modules']::text[],'Build a dynamic product/listing interface.',NULL,NULL,'Write modern, modular JavaScript using functional collection methods.'),
(7,2,'DOM & Browser Programming',ARRAY['DOM','Selecting elements','Modifying HTML','Events','Event listeners','Forms','Form validation','Local storage','Session storage','Dynamic content']::text[],NULL,NULL,'To-Do List Application with add, edit, delete, complete, and local storage features.','Build stateful browser experiences using DOM APIs and storage.'),
(8,2,'APIs & Asynchronous JavaScript',ARRAY['JSON','HTTP requests','REST API concepts','Fetch API','Promises','Async/await','Error handling','Loading states','API responses']::text[],NULL,'Build a Weather / Public API Dashboard.',NULL,'Consume external APIs and handle asynchronous UI states.'),
(9,3,'React Fundamentals',ARRAY['What is React?','React project setup','Components','JSX','Props','State','Events','Conditional rendering','Lists','Keys']::text[],'Build a React component-based website.',NULL,NULL,'Create interfaces from reusable React components.'),
(10,3,'React Hooks & Forms',ARRAY['useState','useEffect','Forms','Controlled components','Form validation','Reusable components','Component communication']::text[],NULL,NULL,'React Student Management Interface','Manage React state, forms, and component communication.'),
(11,3,'React Routing & API Integration',ARRAY['React Router','Routes','Navigation','Dynamic routes','API integration','Fetch/Axios','Loading states','Error handling']::text[],'Connect a React frontend to a public API.',NULL,NULL,'Build multi-page React experiences driven by API data.'),
(12,3,'Advanced React & UI Development',ARRAY['Reusable components','Custom hooks','Context API','State management concepts','Protected routes','Search','Filtering','Pagination','Responsive React UI']::text[],NULL,'Build a React E-Commerce Frontend.',NULL,'Deliver a responsive React application with production-style UI patterns.'),
(13,4,'Node.js Fundamentals',ARRAY['What is Node.js?','Node.js architecture','npm','Package management','Modules','File system','Environment variables','HTTP server','Creating a Node.js application']::text[],'Create a basic Node.js server.',NULL,NULL,'Understand server-side JavaScript and Node project structure.'),
(14,4,'Express.js',ARRAY['Express.js','Application setup','Routes','Middleware','Request/response','Parameters','Query parameters','Error handling','Project structure']::text[],'Build a REST API using Express.',NULL,NULL,'Create organized backend routes and middleware.'),
(15,4,'REST APIs',ARRAY['REST architecture','GET','POST','PUT','PATCH','DELETE','Status codes','JSON responses','API validation','API testing','Postman']::text[],NULL,NULL,'Student Management REST API','Design and test predictable REST endpoints.'),
(16,4,'Authentication & Authorization',ARRAY['Authentication','Authorization','Password hashing','JWT','Login','Registration','Logout','Protected routes','Role-based access','Admin/user permissions','Basic web security']::text[],NULL,'Build a User Authentication System.',NULL,'Secure users, routes, and roles in a backend application.'),
(17,5,'SQL & PostgreSQL',ARRAY['Database fundamentals','PostgreSQL','Tables','Primary keys','Foreign keys','Relationships','CRUD','SQL queries','Joins','Aggregation']::text[],'Create a PostgreSQL database for a web application.',NULL,NULL,'Design and query relational data for web applications.'),
(18,5,'Backend + Database Integration',ARRAY['Connecting Node.js to PostgreSQL','Database queries','CRUD APIs','Data validation','Relationships','Error handling','Database security','Environment variables']::text[],NULL,'Create a Full CRUD Web Application.',NULL,'Persist and validate application data through an API.'),
(19,5,'Full Stack Integration',ARRAY['React + Node.js + Express + PostgreSQL','Frontend/backend communication','API integration','Authentication integration','Protected pages','User dashboard','Error handling','Loading states','Form submission']::text[],NULL,'Build a Full Stack Student/Employee Management System.',NULL,'Connect frontend, backend, authentication, and database layers.'),
(20,5,'Git, GitHub & Docker',ARRAY['Git fundamentals','Repositories','Branches','Commits','Pull Requests','GitHub collaboration','What is Docker?','Images','Containers','Dockerfile','Docker Compose','Environment variables']::text[],'Containerize the full-stack application and push it to GitHub.',NULL,NULL,'Version, collaborate on, and containerize a full-stack project.'),
(21,6,'Web Deployment',ARRAY['Hosting fundamentals','Frontend deployment','Backend deployment','Database deployment','Environment variables','Production builds','Domain concepts','HTTPS','Deployment troubleshooting']::text[],'Deploy the frontend and backend application.',NULL,NULL,'Ship a full-stack application to a production environment.'),
(22,6,'Production Web Development',ARRAY['Performance optimization','Code organization','Security basics','CORS','Rate limiting concepts','Input validation','Error logging','SEO fundamentals','Responsive testing','Browser testing']::text[],NULL,'Optimize and prepare a full-stack application for production.',NULL,'Improve reliability, security, performance, and accessibility.'),
(23,6,'Full Stack Capstone Project',ARRAY['Project idea selection','Requirement analysis','UI/UX planning','Database design','Frontend development','Backend development','API development','Authentication','Database integration','GitHub repository','Testing']::text[],NULL,'Build an e-commerce platform, job portal, learning management system, or online service platform.','Full Stack Capstone Project','Plan and build a complete portfolio-grade web application.'),
(24,6,'Final Deployment & Career Preparation',ARRAY['Final project completion','Testing','Bug fixing','Production deployment','GitHub documentation','README creation','Portfolio website','Resume preparation','Web development interview questions','HTML/CSS interview preparation','JavaScript interview preparation','React interview preparation','Node.js interview preparation','SQL interview preparation','Mock interview','Project presentation','Final evaluation','Certification']::text[],'Present and defend the deployed final project.',NULL,NULL,'Graduate with a documented, deployed portfolio project and interview readiness.')
) AS v(week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
WHERE c.slug = 'web-development'
ON CONFLICT (course_id, week_number) DO UPDATE SET
  month_number = EXCLUDED.month_number, title = EXCLUDED.title, topics = EXCLUDED.topics,
  practical_task = EXCLUDED.practical_task, assignment = EXCLUDED.assignment,
  mini_project = EXCLUDED.mini_project, expected_outcome = EXCLUDED.expected_outcome, updated_at = now();
