UPDATE public.courses
SET title = 'Cloud Computing',
    short_description = 'Learn cloud computing from fundamentals to real-world infrastructure and deployment with AWS, Azure, Linux, Docker, Kubernetes, Terraform, and DevOps.',
    full_description = 'Learn cloud computing from the fundamentals to real-world cloud infrastructure and application deployment. This 6-month program covers cloud concepts, Linux, networking, AWS, Azure, storage, databases, security, Docker, Kubernetes, CI/CD, Infrastructure as Code, monitoring and cloud deployment.',
    level = 'Beginner', duration = '6 Months | 24 Weeks', published_at = COALESCE(published_at, now())
WHERE slug = 'cloud-computing';

INSERT INTO public.course_weeks (course_id, week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
SELECT c.id, v.week_number, v.month_number, v.title, v.topics, v.practical_task, v.assignment, v.mini_project, v.expected_outcome
FROM public.courses c
CROSS JOIN (VALUES
(1,1,'Introduction to Cloud Computing',ARRAY['What is Cloud Computing?','Evolution of cloud computing','Cloud vs traditional infrastructure','Benefits of cloud computing','Public cloud','Private cloud','Hybrid cloud','Community cloud','Cloud service models','IaaS','PaaS','SaaS']::text[],'Identify suitable cloud solutions for different business requirements.',NULL,NULL,'Explain cloud models and match services to business needs.'),
(2,1,'Cloud Architecture & Virtualization',ARRAY['Cloud architecture','Regions','Availability Zones','Data centers','Scalability','Elasticity','High availability','Fault tolerance','Virtual machines','Hypervisors','Virtualization concepts']::text[],'Create and configure a virtual machine.',NULL,NULL,'Design resilient infrastructure using virtualization concepts.'),
(3,1,'Linux Fundamentals',ARRAY['Linux introduction','File system','Files and directories','Linux commands','Permissions','Users and groups','Processes','Package management','Environment variables','SSH']::text[],'Configure a Linux server using SSH.',NULL,NULL,'Operate and secure a Linux server from the command line.'),
(4,1,'Networking Fundamentals',ARRAY['Networking basics','IP addresses','IPv4 and IPv6','Subnets','DNS','DHCP','HTTP/HTTPS','TCP/IP','Ports','Firewalls','Load balancing concepts']::text[],NULL,NULL,'Design a basic cloud network architecture.','Understand the network path between users, services, and infrastructure.'),
(5,2,'AWS Fundamentals',ARRAY['Introduction to AWS','AWS account structure','AWS Management Console','IAM','Users','Groups','Roles','Policies','Regions','Availability Zones']::text[],'Create IAM users and configure permissions.',NULL,NULL,'Navigate AWS and apply basic identity controls.'),
(6,2,'AWS Compute',ARRAY['Amazon EC2','Instance types','AMIs','Key pairs','Security groups','Elastic IP','Auto Scaling','Load Balancers','Server deployment']::text[],NULL,'Deploy a web application on EC2.',NULL,'Deploy and scale a web workload on AWS compute.'),
(7,2,'AWS Storage & Databases',ARRAY['Amazon S3','Buckets','Objects','Storage classes','Versioning','Lifecycle policies','RDS','Relational databases','DynamoDB basics','Backup concepts']::text[],'Build an S3-based file storage system.',NULL,NULL,'Choose and configure cloud storage and database services.'),
(8,2,'Azure Fundamentals',ARRAY['Introduction to Microsoft Azure','Azure Portal','Resource Groups','Azure Virtual Machines','Azure Storage','Azure SQL','Azure networking','Azure identity','Azure Monitor']::text[],NULL,NULL,'Deploy an application using Azure services.','Map core AWS concepts to Azure services and deploy a workload.'),
(9,3,'Cloud Networking',ARRAY['Virtual Private Cloud','VPC architecture','Subnets','Route tables','Internet Gateway','NAT Gateway','Security Groups','Network ACLs','Load Balancers']::text[],'Build a secure AWS VPC architecture.',NULL,NULL,'Design segmented, private, and public cloud networks.'),
(10,3,'Cloud Databases',ARRAY['Cloud database concepts','Relational databases','NoSQL databases','AWS RDS','DynamoDB','Azure SQL','Database backups','Replication','High availability']::text[],'Deploy and connect a cloud database to an application.',NULL,NULL,'Select a database architecture for availability and scale.'),
(11,3,'Cloud Security & IAM',ARRAY['Cloud security fundamentals','Identity and Access Management','Least privilege','Authentication','Authorization','Encryption','Key management','Secrets management','Security monitoring','Common cloud security risks']::text[],NULL,'Secure a cloud application using IAM and encryption.',NULL,'Apply least privilege, encryption, and security monitoring.'),
(12,3,'Cloud Monitoring & Cost Management',ARRAY['Cloud monitoring','AWS CloudWatch','Azure Monitor','Logs','Metrics','Alerts','Resource monitoring','Cloud billing','Cost optimization','Reserved/discounted resources concepts']::text[],NULL,NULL,'Create a cloud monitoring and alerting setup.','Monitor service health and control cloud spend.'),
(13,4,'Docker Fundamentals',ARRAY['What is Docker?','Containers vs virtual machines','Docker architecture','Images','Containers','Docker commands','Docker Hub','Dockerfiles']::text[],'Containerize a web application.',NULL,NULL,'Build and run a portable containerized application.'),
(14,4,'Advanced Docker',ARRAY['Docker Compose','Volumes','Networks','Environment variables','Multi-container applications','Image optimization','Container security','Docker registries']::text[],NULL,'Create a multi-container application.',NULL,'Compose and secure multi-service container deployments.'),
(15,4,'Kubernetes Fundamentals',ARRAY['What is Kubernetes?','Kubernetes architecture','Cluster','Nodes','Pods','Deployments','Services','Namespaces','ConfigMaps','Secrets']::text[],'Deploy an application to a Kubernetes cluster.',NULL,NULL,'Deploy workloads and configuration to Kubernetes.'),
(16,4,'Kubernetes Advanced',ARRAY['ReplicaSets','Scaling','Rolling updates','Rollbacks','Ingress','Persistent volumes','Health checks','Kubernetes networking','Kubernetes security']::text[],NULL,NULL,'Deploy a scalable application using Kubernetes.','Operate a resilient, scalable Kubernetes service.'),
(17,5,'Git & GitHub',ARRAY['Git fundamentals','Repositories','Commits','Branches','Merging','Pull requests','GitHub workflows','.gitignore','Collaboration']::text[],'Create and manage a cloud project repository.',NULL,NULL,'Use version control for collaborative infrastructure work.'),
(18,5,'CI/CD',ARRAY['What is CI/CD?','Continuous Integration','Continuous Delivery','Continuous Deployment','GitHub Actions','Build pipelines','Automated testing','Deployment pipelines']::text[],NULL,'Create a CI/CD pipeline for a cloud application.',NULL,'Automate testing and repeatable application delivery.'),
(19,5,'Infrastructure as Code',ARRAY['Infrastructure as Code concepts','Terraform introduction','Providers','Resources','Variables','Outputs','State','Terraform plan','Terraform apply','Infrastructure automation']::text[],'Deploy cloud infrastructure using Terraform.',NULL,NULL,'Provision repeatable infrastructure from versioned code.'),
(20,5,'Cloud DevOps Integration',ARRAY['GitHub','Docker','Kubernetes','Terraform','AWS/Azure','CI/CD']::text[],NULL,NULL,'Build an automated cloud deployment pipeline.','Combine development and infrastructure automation into one workflow.'),
(21,6,'Serverless & Cloud-Native Architecture',ARRAY['Serverless computing','AWS Lambda','Azure Functions','API Gateway','Event-driven architecture','Microservices','Cloud-native applications','Message queues']::text[],'Build a serverless API.',NULL,NULL,'Design event-driven services with managed cloud components.'),
(22,6,'Cloud Architecture & Production Deployment',ARRAY['Scalable architecture','High availability','Disaster recovery','Backup strategies','Load balancing','Auto scaling','Monitoring','Security','Cost optimization']::text[],NULL,'Design a production-ready cloud architecture.',NULL,'Plan a secure, resilient, and cost-aware production system.'),
(23,6,'Cloud Computing Capstone',ARRAY['Application','Docker','Cloud Infrastructure','Database','CI/CD','Monitoring','Security','Deployment']::text[],NULL,'Develop a cloud project such as an LMS, e-commerce platform, job portal, file storage system, hospital system, student management system, scalable business application, or microservices application.',NULL,'Deliver a complete cloud project from application to deployment.'),
(24,6,'Final Deployment & Career Preparation',ARRAY['Final project completion','Production deployment','Cloud security review','Performance optimization','Monitoring setup','Documentation','GitHub portfolio','Cloud interview preparation','AWS interview questions','Azure interview questions','Linux interview preparation','DevOps interview preparation','Resume preparation','Mock interview','Final project presentation','Final evaluation','Certification']::text[],'Present and defend the production cloud deployment.',NULL,NULL,'Graduate with a documented cloud portfolio project and certification.')
) AS v(week_number, month_number, title, topics, practical_task, assignment, mini_project, expected_outcome)
WHERE c.slug = 'cloud-computing'
ON CONFLICT (course_id, week_number) DO UPDATE SET
  month_number = EXCLUDED.month_number, title = EXCLUDED.title, topics = EXCLUDED.topics,
  practical_task = EXCLUDED.practical_task, assignment = EXCLUDED.assignment,
  mini_project = EXCLUDED.mini_project, expected_outcome = EXCLUDED.expected_outcome, updated_at = now();
